# 服务配置
service:
  host: "192.168.221.1"
  port: 8000

nacos:
  enabled: False
  server_addr: "http://192.168.233.128:8848"
  group: "DEFAULT_GROUP"
  service_name: "yolo-service"

# MediaMTX 基础地址
mediamtx:
  host: "192.168.233.128"
  rtsp_port: 8554

# YOLO 推理
yolo:
  default_model: "../yolo11n.pt"    # 默认模型路径
  target_fps: 15                     # 推流目标帧率
  stream_connect_timeout: 5          # 拉流超时（秒）
  frame_skip: 3   # 1表示逐帧检测

rabbitmq:
  host: "192.168.233.128"
  port: 5672
  virtual_host: "/"
  username: "YLZ"
  password: "123"
  exchange: "yolo.direct.exchange"   # 交换机名称
  routing_key: "yolo.statistics"     # 路由键
  error_routing_key: "yolo.error"
  end_routing_key: "yolo.end"
  stats_interval: 30                 # 统计发送间隔（秒）

# 图片检测结果保存目录
temp_img: "./model_results"
# 原始图片保存目录
origin_img: "./origin_img"